apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nodes
spec:
  replicas: {{ .Values.replicaCount.nodes }}
  podManagementPolicy: "Parallel"
  serviceName: {{ .Release.Name }}-service
  selector:
    matchLabels:
      app: zerotenkay
  template:
    metadata:
      labels:
        app: zerotenkay
    spec:
      dnsConfig:
        searches:
          - "{{ .Release.Name }}-bootstrap"
      volumes:
        - name: enr-data
          emptyDir: {}
      initContainers:
      {{- if .Values.artificialLatency.enabled }}
        - name: tc-setup
          image: alpine
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              apk add --no-cache iproute2
              tc qdisc add dev eth0 root netem delay {{ .Values.artificialLatency.latencyMs }}ms
      {{- end }}
        - name: grabenr
          image: soutullostatus/getenr:v0.5.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: enr-data
              mountPath: /etc/enr
          command:
            - /app/getenr.sh
          args:
            - "3"
            - "{{ .Release.Name }}-bootstrap"
      containers:
        - name: waku
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8645
            - containerPort: 8008
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: enr-data
              mountPath: /etc/enr
          resources:
            {{- toYaml .Values.nodes.resources | nindent 12 }}
          command:
            - /bin/sh
            - -c
          args:
            {{- toYaml .Values.nodes.command | nindent 12 }}
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
